### PR TITLE
Biometrics

### PR DESCRIPTION
**Pull request by Gunnar-Stunnar**
Put in Biometrics to block screen when user is not at phone for 10 seconds

### CODE REVIEW

**Comment by juanky201271** [comment]
@zancas @Gunnar-Stunnar If I understand you ok, You supposedly have to keep working on this. I was testing this new feature, but I can't do anything after the screen got blurred... As I said, maybe I'm doing something wrong.

I did two initial tests:
- Without any Face recognition configuration in my device. Nothing happened. I was expecting some message like this: 'If you don't set up your Face recognition feature you can not use the wallet'... (I don't know what It could happen if you have other bio metric feature active in your device, like Touch - finger print).
- With my Face recognition configured. Nothing happened. I was expecting a prompt asking to me to do something.

**Comment by zancas** [comment]
Are there updates on these manual tests @juanky201271 ?
Are you still unable to get past the blur screen?

**Comment by juanky201271** [comment]
@zancas nope! I can't do anything since the screen get blur... I can use the app during 10 seconds.

**Comment by zancas** [comment]
This PR doesn't have much info on it..

**Pull request closed without merging**
